export const NOTEBOOK_EVENTS = {
  NEW_NOTEBOOK_CREATED: 'notebook_new_notebook_created',
  NOTEBOOK_EXPORTED: 'notebook_exported',
  NOTEBOOK_IMPORTED: 'notebook_imported',
  NOTEBOOK_DELETED: 'notebook_deleted',
  NOTEBOOK_RENAMED: 'notebook_renamed',
  NOTEBOOK_SHARED: 'notebook_shared',
  NOTEBOOK_UNSHARED: 'notebook_unshared',
  NOTEBOOK_LOCKED: 'notebook_locked',
  NOTEBOOK_UNLOCKED: 'notebook_unlocked',
  NOTEBOOK_PINNED: 'notebook_pinned',
  NOTEBOOK_UNPINNED: 'notebook_unpinned',

  NOTEBOOK_RUN_QUERY: 'notebook_run_query',
  NOTEBOOK_RUN_QUERY_FAILED: 'notebook_run_query_failed',
  NOTEBOOK_RUN_QUERY_SUCCESS: 'notebook_run_query_success',
  NOTEBOOK_RUN_QUERY_PARTIAL_SUCCESS: 'notebook_run_query_partial_success',
  NOTEBOOK_RUN_QUERY_ERROR: 'notebook_run_query_error',
  NOTEBOOK_RUN_QUERY_CANCELLED: 'notebook_run_query_cancelled',
  NOTEBOOK_RUN_QUERY_TIMEOUT: 'notebook_run_query_timeout',
};
