packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@storybook/addon-docs': ^10.3.5
  '@storybook/addon-links': ^10.3.4
  '@storybook/react': ^10.3.4
  '@storybook/react-vite': ^10.3.4
  '@supabase/supabase-js': ^2.86.2
  '@tanstack/react-query': ^5.90.12
  '@tanstack/react-query-devtools': ^5.91.1
  '@tanstack/react-router': 1.169.2
  '@types/node': ^24.9.2
  '@types/react': ^19.2.3
  '@types/react-dom': ^19.2.3
  '@vitest/coverage-istanbul': ^4.0.18
  ai: 6.0.150
  date-fns: ^4.1.0
  msw: ^2.12.4
  react: ^19.2.3
  react-dom: ^19.2.3
  storybook: ^10.3.4
  supabase: 2.87.2
  typescript: ^5.9.3
  uuid: ^11.0.3
  vite: ^7.1.12
  vitest: ^4.0.18
  zod: ^4.0.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@sentry/cli'
