/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as JoinIndexRouteImport } from './routes/join/index'
import { Route as PrjProjectSlugRouteImport } from './routes/prj/$projectSlug'
import { Route as JoinAcceptRouteImport } from './routes/join/accept'
import { Route as IngestSplatRouteImport } from './routes/ingest.$'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthPasswordResetRouteImport } from './routes/auth/password-reset'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AuthCallbackErrorRouteImport } from './routes/auth/callback-error'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AgentConversationSlugRouteImport } from './routes/agent/$conversationSlug'
import { Route as FlatPrefixSplatRouteImport } from './routes/$flatPrefix.$'
import { Route as PrjProjectSlugIndexRouteImport } from './routes/prj/$projectSlug/index'
import { Route as DocsSlugIndexRouteImport } from './routes/docs/$slug/index'
import { Route as ApiDocsIndexRouteImport } from './routes/api/docs/index'
import { Route as PrjProjectSlugNewTabRouteImport } from './routes/prj/$projectSlug/new-tab'
import { Route as PrjProjectSlugRouteBaseRouteImport } from './routes/prj/$projectSlug/$routeBase'
import { Route as ApiDocsImportRouteImport } from './routes/api/docs/import'
import { Route as ApiDocsSlugRouteImport } from './routes/api/docs/$slug'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiBillingStatusRouteImport } from './routes/api/billing/status'
import { Route as ApiBillingInvoiceRouteImport } from './routes/api/billing/invoice'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiDocsSlugUploadRouteImport } from './routes/api/docs/$slug/upload'
import { Route as ApiDocsSlugPreviewRouteImport } from './routes/api/docs/$slug/preview'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrjProjectSlugRoute = PrjProjectSlugRouteImport.update({
  id: '/prj/$projectSlug',
  path: '/prj/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinAcceptRoute = JoinAcceptRouteImport.update({
  id: '/join/accept',
  path: '/join/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestSplatRoute = IngestSplatRouteImport.update({
  id: '/ingest/$',
  path: '/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPasswordResetRoute = AuthPasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackErrorRoute = AuthCallbackErrorRouteImport.update({
  id: '/callback-error',
  path: '/callback-error',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AgentConversationSlugRoute = AgentConversationSlugRouteImport.update({
  id: '/agent/$conversationSlug',
  path: '/agent/$conversationSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const FlatPrefixSplatRoute = FlatPrefixSplatRouteImport.update({
  id: '/$flatPrefix/$',
  path: '/$flatPrefix/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrjProjectSlugIndexRoute = PrjProjectSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrjProjectSlugRoute,
} as any)
const DocsSlugIndexRoute = DocsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsSlugRoute,
} as any)
const ApiDocsIndexRoute = ApiDocsIndexRouteImport.update({
  id: '/api/docs/',
  path: '/api/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrjProjectSlugNewTabRoute = PrjProjectSlugNewTabRouteImport.update({
  id: '/new-tab',
  path: '/new-tab',
  getParentRoute: () => PrjProjectSlugRoute,
} as any)
const PrjProjectSlugRouteBaseRoute = PrjProjectSlugRouteBaseRouteImport.update({
  id: '/$routeBase',
  path: '/$routeBase',
  getParentRoute: () => PrjProjectSlugRoute,
} as any)
const ApiDocsImportRoute = ApiDocsImportRouteImport.update({
  id: '/api/docs/import',
  path: '/api/docs/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsSlugRoute = ApiDocsSlugRouteImport.update({
  id: '/api/docs/$slug',
  path: '/api/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingStatusRoute = ApiBillingStatusRouteImport.update({
  id: '/api/billing/status',
  path: '/api/billing/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingInvoiceRoute = ApiBillingInvoiceRouteImport.update({
  id: '/api/billing/invoice',
  path: '/api/billing/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsSlugUploadRoute = ApiDocsSlugUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApiDocsSlugRoute,
} as any)
const ApiDocsSlugPreviewRoute = ApiDocsSlugPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ApiDocsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/update-password': typeof UpdatePasswordRoute
  '/$flatPrefix/$': typeof FlatPrefixSplatRoute
  '/agent/$conversationSlug': typeof AgentConversationSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/callback-error': typeof AuthCallbackErrorRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/docs/$slug': typeof DocsSlugRouteWithChildren
  '/ingest/$': typeof IngestSplatRoute
  '/join/accept': typeof JoinAcceptRoute
  '/prj/$projectSlug': typeof PrjProjectSlugRouteWithChildren
  '/join/': typeof JoinIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/invoice': typeof ApiBillingInvoiceRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/docs/$slug': typeof ApiDocsSlugRouteWithChildren
  '/api/docs/import': typeof ApiDocsImportRoute
  '/prj/$projectSlug/$routeBase': typeof PrjProjectSlugRouteBaseRoute
  '/prj/$projectSlug/new-tab': typeof PrjProjectSlugNewTabRoute
  '/api/docs/': typeof ApiDocsIndexRoute
  '/docs/$slug/': typeof DocsSlugIndexRoute
  '/prj/$projectSlug/': typeof PrjProjectSlugIndexRoute
  '/api/docs/$slug/preview': typeof ApiDocsSlugPreviewRoute
  '/api/docs/$slug/upload': typeof ApiDocsSlugUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/update-password': typeof UpdatePasswordRoute
  '/$flatPrefix/$': typeof FlatPrefixSplatRoute
  '/agent/$conversationSlug': typeof AgentConversationSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/callback-error': typeof AuthCallbackErrorRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/ingest/$': typeof IngestSplatRoute
  '/join/accept': typeof JoinAcceptRoute
  '/join': typeof JoinIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/invoice': typeof ApiBillingInvoiceRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/docs/$slug': typeof ApiDocsSlugRouteWithChildren
  '/api/docs/import': typeof ApiDocsImportRoute
  '/prj/$projectSlug/$routeBase': typeof PrjProjectSlugRouteBaseRoute
  '/prj/$projectSlug/new-tab': typeof PrjProjectSlugNewTabRoute
  '/api/docs': typeof ApiDocsIndexRoute
  '/docs/$slug': typeof DocsSlugIndexRoute
  '/prj/$projectSlug': typeof PrjProjectSlugIndexRoute
  '/api/docs/$slug/preview': typeof ApiDocsSlugPreviewRoute
  '/api/docs/$slug/upload': typeof ApiDocsSlugUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/update-password': typeof UpdatePasswordRoute
  '/$flatPrefix/$': typeof FlatPrefixSplatRoute
  '/agent/$conversationSlug': typeof AgentConversationSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/callback-error': typeof AuthCallbackErrorRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/docs/$slug': typeof DocsSlugRouteWithChildren
  '/ingest/$': typeof IngestSplatRoute
  '/join/accept': typeof JoinAcceptRoute
  '/prj/$projectSlug': typeof PrjProjectSlugRouteWithChildren
  '/join/': typeof JoinIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/invoice': typeof ApiBillingInvoiceRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/docs/$slug': typeof ApiDocsSlugRouteWithChildren
  '/api/docs/import': typeof ApiDocsImportRoute
  '/prj/$projectSlug/$routeBase': typeof PrjProjectSlugRouteBaseRoute
  '/prj/$projectSlug/new-tab': typeof PrjProjectSlugNewTabRoute
  '/api/docs/': typeof ApiDocsIndexRoute
  '/docs/$slug/': typeof DocsSlugIndexRoute
  '/prj/$projectSlug/': typeof PrjProjectSlugIndexRoute
  '/api/docs/$slug/preview': typeof ApiDocsSlugPreviewRoute
  '/api/docs/$slug/upload': typeof ApiDocsSlugUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/update-password'
    | '/$flatPrefix/$'
    | '/agent/$conversationSlug'
    | '/auth/callback'
    | '/auth/callback-error'
    | '/auth/confirm'
    | '/auth/password-reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/docs/$slug'
    | '/ingest/$'
    | '/join/accept'
    | '/prj/$projectSlug'
    | '/join/'
    | '/organizations/'
    | '/api/billing/checkout'
    | '/api/billing/invoice'
    | '/api/billing/status'
    | '/api/billing/webhook'
    | '/api/docs/$slug'
    | '/api/docs/import'
    | '/prj/$projectSlug/$routeBase'
    | '/prj/$projectSlug/new-tab'
    | '/api/docs/'
    | '/docs/$slug/'
    | '/prj/$projectSlug/'
    | '/api/docs/$slug/preview'
    | '/api/docs/$slug/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/update-password'
    | '/$flatPrefix/$'
    | '/agent/$conversationSlug'
    | '/auth/callback'
    | '/auth/callback-error'
    | '/auth/confirm'
    | '/auth/password-reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/ingest/$'
    | '/join/accept'
    | '/join'
    | '/organizations'
    | '/api/billing/checkout'
    | '/api/billing/invoice'
    | '/api/billing/status'
    | '/api/billing/webhook'
    | '/api/docs/$slug'
    | '/api/docs/import'
    | '/prj/$projectSlug/$routeBase'
    | '/prj/$projectSlug/new-tab'
    | '/api/docs'
    | '/docs/$slug'
    | '/prj/$projectSlug'
    | '/api/docs/$slug/preview'
    | '/api/docs/$slug/upload'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/docs'
    | '/update-password'
    | '/$flatPrefix/$'
    | '/agent/$conversationSlug'
    | '/auth/callback'
    | '/auth/callback-error'
    | '/auth/confirm'
    | '/auth/password-reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/docs/$slug'
    | '/ingest/$'
    | '/join/accept'
    | '/prj/$projectSlug'
    | '/join/'
    | '/organizations/'
    | '/api/billing/checkout'
    | '/api/billing/invoice'
    | '/api/billing/status'
    | '/api/billing/webhook'
    | '/api/docs/$slug'
    | '/api/docs/import'
    | '/prj/$projectSlug/$routeBase'
    | '/prj/$projectSlug/new-tab'
    | '/api/docs/'
    | '/docs/$slug/'
    | '/prj/$projectSlug/'
    | '/api/docs/$slug/preview'
    | '/api/docs/$slug/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  FlatPrefixSplatRoute: typeof FlatPrefixSplatRoute
  AgentConversationSlugRoute: typeof AgentConversationSlugRoute
  IngestSplatRoute: typeof IngestSplatRoute
  JoinAcceptRoute: typeof JoinAcceptRoute
  PrjProjectSlugRoute: typeof PrjProjectSlugRouteWithChildren
  JoinIndexRoute: typeof JoinIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingInvoiceRoute: typeof ApiBillingInvoiceRoute
  ApiBillingStatusRoute: typeof ApiBillingStatusRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiDocsSlugRoute: typeof ApiDocsSlugRouteWithChildren
  ApiDocsImportRoute: typeof ApiDocsImportRoute
  ApiDocsIndexRoute: typeof ApiDocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prj/$projectSlug': {
      id: '/prj/$projectSlug'
      path: '/prj/$projectSlug'
      fullPath: '/prj/$projectSlug'
      preLoaderRoute: typeof PrjProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/accept': {
      id: '/join/accept'
      path: '/join/accept'
      fullPath: '/join/accept'
      preLoaderRoute: typeof JoinAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest/$': {
      id: '/ingest/$'
      path: '/ingest/$'
      fullPath: '/ingest/$'
      preLoaderRoute: typeof IngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/password-reset': {
      id: '/auth/password-reset'
      path: '/password-reset'
      fullPath: '/auth/password-reset'
      preLoaderRoute: typeof AuthPasswordResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback-error': {
      id: '/auth/callback-error'
      path: '/callback-error'
      fullPath: '/auth/callback-error'
      preLoaderRoute: typeof AuthCallbackErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/agent/$conversationSlug': {
      id: '/agent/$conversationSlug'
      path: '/agent/$conversationSlug'
      fullPath: '/agent/$conversationSlug'
      preLoaderRoute: typeof AgentConversationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$flatPrefix/$': {
      id: '/$flatPrefix/$'
      path: '/$flatPrefix/$'
      fullPath: '/$flatPrefix/$'
      preLoaderRoute: typeof FlatPrefixSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prj/$projectSlug/': {
      id: '/prj/$projectSlug/'
      path: '/'
      fullPath: '/prj/$projectSlug/'
      preLoaderRoute: typeof PrjProjectSlugIndexRouteImport
      parentRoute: typeof PrjProjectSlugRoute
    }
    '/docs/$slug/': {
      id: '/docs/$slug/'
      path: '/'
      fullPath: '/docs/$slug/'
      preLoaderRoute: typeof DocsSlugIndexRouteImport
      parentRoute: typeof DocsSlugRoute
    }
    '/api/docs/': {
      id: '/api/docs/'
      path: '/api/docs'
      fullPath: '/api/docs/'
      preLoaderRoute: typeof ApiDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prj/$projectSlug/new-tab': {
      id: '/prj/$projectSlug/new-tab'
      path: '/new-tab'
      fullPath: '/prj/$projectSlug/new-tab'
      preLoaderRoute: typeof PrjProjectSlugNewTabRouteImport
      parentRoute: typeof PrjProjectSlugRoute
    }
    '/prj/$projectSlug/$routeBase': {
      id: '/prj/$projectSlug/$routeBase'
      path: '/$routeBase'
      fullPath: '/prj/$projectSlug/$routeBase'
      preLoaderRoute: typeof PrjProjectSlugRouteBaseRouteImport
      parentRoute: typeof PrjProjectSlugRoute
    }
    '/api/docs/import': {
      id: '/api/docs/import'
      path: '/api/docs/import'
      fullPath: '/api/docs/import'
      preLoaderRoute: typeof ApiDocsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/$slug': {
      id: '/api/docs/$slug'
      path: '/api/docs/$slug'
      fullPath: '/api/docs/$slug'
      preLoaderRoute: typeof ApiDocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/status': {
      id: '/api/billing/status'
      path: '/api/billing/status'
      fullPath: '/api/billing/status'
      preLoaderRoute: typeof ApiBillingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/invoice': {
      id: '/api/billing/invoice'
      path: '/api/billing/invoice'
      fullPath: '/api/billing/invoice'
      preLoaderRoute: typeof ApiBillingInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/$slug/upload': {
      id: '/api/docs/$slug/upload'
      path: '/upload'
      fullPath: '/api/docs/$slug/upload'
      preLoaderRoute: typeof ApiDocsSlugUploadRouteImport
      parentRoute: typeof ApiDocsSlugRoute
    }
    '/api/docs/$slug/preview': {
      id: '/api/docs/$slug/preview'
      path: '/preview'
      fullPath: '/api/docs/$slug/preview'
      preLoaderRoute: typeof ApiDocsSlugPreviewRouteImport
      parentRoute: typeof ApiDocsSlugRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCallbackErrorRoute: typeof AuthCallbackErrorRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCallbackErrorRoute: AuthCallbackErrorRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DocsSlugRouteChildren {
  DocsSlugIndexRoute: typeof DocsSlugIndexRoute
}

const DocsSlugRouteChildren: DocsSlugRouteChildren = {
  DocsSlugIndexRoute: DocsSlugIndexRoute,
}

const DocsSlugRouteWithChildren = DocsSlugRoute._addFileChildren(
  DocsSlugRouteChildren,
)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRouteWithChildren
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRouteWithChildren,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface PrjProjectSlugRouteChildren {
  PrjProjectSlugRouteBaseRoute: typeof PrjProjectSlugRouteBaseRoute
  PrjProjectSlugNewTabRoute: typeof PrjProjectSlugNewTabRoute
  PrjProjectSlugIndexRoute: typeof PrjProjectSlugIndexRoute
}

const PrjProjectSlugRouteChildren: PrjProjectSlugRouteChildren = {
  PrjProjectSlugRouteBaseRoute: PrjProjectSlugRouteBaseRoute,
  PrjProjectSlugNewTabRoute: PrjProjectSlugNewTabRoute,
  PrjProjectSlugIndexRoute: PrjProjectSlugIndexRoute,
}

const PrjProjectSlugRouteWithChildren = PrjProjectSlugRoute._addFileChildren(
  PrjProjectSlugRouteChildren,
)

interface ApiDocsSlugRouteChildren {
  ApiDocsSlugPreviewRoute: typeof ApiDocsSlugPreviewRoute
  ApiDocsSlugUploadRoute: typeof ApiDocsSlugUploadRoute
}

const ApiDocsSlugRouteChildren: ApiDocsSlugRouteChildren = {
  ApiDocsSlugPreviewRoute: ApiDocsSlugPreviewRoute,
  ApiDocsSlugUploadRoute: ApiDocsSlugUploadRoute,
}

const ApiDocsSlugRouteWithChildren = ApiDocsSlugRoute._addFileChildren(
  ApiDocsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  UpdatePasswordRoute: UpdatePasswordRoute,
  FlatPrefixSplatRoute: FlatPrefixSplatRoute,
  AgentConversationSlugRoute: AgentConversationSlugRoute,
  IngestSplatRoute: IngestSplatRoute,
  JoinAcceptRoute: JoinAcceptRoute,
  PrjProjectSlugRoute: PrjProjectSlugRouteWithChildren,
  JoinIndexRoute: JoinIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingInvoiceRoute: ApiBillingInvoiceRoute,
  ApiBillingStatusRoute: ApiBillingStatusRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiDocsSlugRoute: ApiDocsSlugRouteWithChildren,
  ApiDocsImportRoute: ApiDocsImportRoute,
  ApiDocsIndexRoute: ApiDocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
