import * as React from 'react';
import { useState, useEffect } from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { ReportRenderer } from './report-renderer';
import { executeReport } from './execute-report';
import type { QueryFn } from './types';

const meta: Meta<typeof ReportRenderer> = {
  title: 'Design System/Report/Renderer',
  component: ReportRenderer,
};

export default meta;
type Story = StoryObj<typeof ReportRenderer>;

// Static report — vega-lite specs with data already inlined
const STATIC_REPORT = `---
title: "Q4 2024 Sales Performance Report"
author: "Qwery Analytics"
date: "2024-12-15"
tags: ["sales", "quarterly", "revenue"]
summary: "Analysis of Q4 sales trends showing 23% growth over Q3"
---

# Q4 2024 Sales Performance

## Executive Summary

Our Q4 performance exceeded expectations with total revenue reaching $2.4M, representing a **23% increase** over Q3. The growth was primarily driven by enterprise customers in the technology sector.

## Monthly Revenue Trends

The following chart shows our monthly revenue progression throughout Q4:

\`\`\`vega-lite
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"month": "2024-10", "revenue": 720000},
      {"month": "2024-11", "revenue": 850000},
      {"month": "2024-12", "revenue": 830000}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": { "field": "month", "type": "temporal", "title": "Month" },
    "y": { "field": "revenue", "type": "quantitative", "title": "Revenue (USD)", "axis": { "format": "$,.0f" } }
  },
  "width": 600,
  "height": 300
}
\`\`\`

November showed the strongest performance with $850K in revenue, though December saw a slight dip likely due to holiday seasonality.

## Customer Segmentation

\`\`\`vega-lite
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"segment": "Enterprise", "revenue": 1200000},
      {"segment": "Mid-Market", "revenue": 800000},
      {"segment": "SMB", "revenue": 400000}
    ]
  },
  "mark": "arc",
  "encoding": {
    "theta": { "field": "revenue", "type": "quantitative" },
    "color": { "field": "segment", "type": "nominal", "title": "Customer Segment" }
  },
  "view": { "stroke": null },
  "width": 400,
  "height": 400
}
\`\`\`

Enterprise customers now represent **50%** of total revenue, up from 42% in Q3.

## Recommendations

Based on this analysis, we recommend:

1. **Double down on enterprise sales** - The data clearly shows this is our strongest growth segment
2. **Investigate December dip** - Understanding seasonal patterns will help with Q4 2025 planning
3. **SMB retention focus** - While smaller in absolute terms, SMB customers show promise for expansion

---

*Report generated by Qwery on 2024-12-15*
`;

export const StaticReport: Story = {
  args: {
    content: STATIC_REPORT,
  },
};

// Dynamic report — JS code blocks that get executed via a mock queryFn (same use case as notebook)
const DYNAMIC_REPORT = `---
title: "2025 Investor Report"
author: "Acme SaaS"
date: "2026-02-15"
tags: ["investors", "annual", "metrics", "growth", "dynamic"]
summary: "Full year product and revenue metrics for Series A investors — generated dynamically from SQL"
---

# 2025 Investor Report

## Executive Summary

Acme SaaS delivered strong performance in 2025. **MRR grew 379%** from $58K to $279K, while active users increased 302% to nearly 5,000. Engagement improved from 54.2 to 76.4, and churn dropped from 5.1% to 2.6%, demonstrating product-market fit and retention gains.

## Monthly Recurring Revenue

\`\`\`js
const mrrData = await extension.query(\`
  SELECT date_trunc('month', created_at) AS month, SUM(mrr) AS mrr
  FROM product_metrics
  WHERE created_at >= '2025-01-01' AND created_at < '2026-01-01'
  GROUP BY date_trunc('month', created_at)
  ORDER BY month
\`);

display(vegaLite({
  data: { values: mrrData },
  mark: { type: 'line', point: true },
  encoding: {
    x: { field: 'month', type: 'temporal', title: 'Month' },
    y: { field: 'mrr', type: 'quantitative', title: 'MRR (USD)', axis: { format: '$,.0f' } }
  },
  width: 600,
  height: 300
}));
\`\`\`

## User Growth

\`\`\`js
const userGrowthData = await extension.query(\`
  SELECT month, metric, count FROM user_metrics
  WHERE metric IN ('New Users', 'Active Users (MAU)')
  ORDER BY month, metric
\`);

display(vegaLite({
  data: { values: userGrowthData },
  mark: { type: 'line', point: true },
  encoding: {
    x: { field: 'month', type: 'temporal', title: 'Month' },
    y: { field: 'count', type: 'quantitative', title: 'Users' },
    color: { field: 'metric', type: 'nominal', title: '' }
  },
  width: 600,
  height: 300
}));
\`\`\`

## Engagement & Retention

\`\`\`js
const engagementData = await extension.query(\`
  SELECT date_trunc('month', created_at) AS month, AVG(engagement_score) AS engagement_score
  FROM product_metrics
  WHERE created_at >= '2025-01-01' AND created_at < '2026-01-01'
  GROUP BY date_trunc('month', created_at)
  ORDER BY month
\`);

display(vegaLite({
  data: { values: engagementData },
  mark: { type: 'area', line: true, opacity: 0.85 },
  encoding: {
    x: { field: 'month', type: 'temporal', title: 'Month' },
    y: { field: 'engagement_score', type: 'quantitative', title: 'Engagement Score', scale: { domain: [50, 85] } },
    y2: { datum: 50 },
    color: { value: '#6366f1', legend: null }
  },
  width: 600,
  height: 300
}));
\`\`\`

Engagement improved from 54.2 to **76.4** over the year. Churn decreased from 5.1% to **2.6%**, below our 3% target.

## Key Takeaways

1. **Revenue acceleration** — MRR growth rate increased each month
2. **Efficient acquisition** — New user signups up 161% with improving activation
3. **Strong retention** — Churn below target; expansion revenue contributing
4. **Product engagement** — Score trending toward 80 target

---

*Report generated for Acme SaaS Board — February 2026*
`;

const mrrData = [
  { month: '2025-01-01', mrr: 58200 },
  { month: '2025-02-01', mrr: 64100 },
  { month: '2025-03-01', mrr: 71800 },
  { month: '2025-04-01', mrr: 82400 },
  { month: '2025-05-01', mrr: 94800 },
  { month: '2025-06-01', mrr: 108900 },
  { month: '2025-07-01', mrr: 124500 },
  { month: '2025-08-01', mrr: 142800 },
  { month: '2025-09-01', mrr: 168200 },
  { month: '2025-10-01', mrr: 198400 },
  { month: '2025-11-01', mrr: 235600 },
  { month: '2025-12-01', mrr: 278900 },
];

const userGrowthData = [
  { month: '2025-01', metric: 'New Users', count: 156 },
  { month: '2025-02', metric: 'New Users', count: 182 },
  { month: '2025-03', metric: 'New Users', count: 214 },
  { month: '2025-04', metric: 'New Users', count: 248 },
  { month: '2025-05', metric: 'New Users', count: 286 },
  { month: '2025-06', metric: 'New Users', count: 312 },
  { month: '2025-07', metric: 'New Users', count: 342 },
  { month: '2025-08', metric: 'New Users', count: 418 },
  { month: '2025-09', metric: 'New Users', count: 521 },
  { month: '2025-10', metric: 'New Users', count: 612 },
  { month: '2025-11', metric: 'New Users', count: 734 },
  { month: '2025-12', metric: 'New Users', count: 892 },
  { month: '2025-01', metric: 'Active Users (MAU)', count: 1240 },
  { month: '2025-02', metric: 'Active Users (MAU)', count: 1380 },
  { month: '2025-03', metric: 'Active Users (MAU)', count: 1540 },
  { month: '2025-04', metric: 'Active Users (MAU)', count: 1720 },
  { month: '2025-05', metric: 'Active Users (MAU)', count: 1980 },
  { month: '2025-06', metric: 'Active Users (MAU)', count: 2280 },
  { month: '2025-07', metric: 'Active Users (MAU)', count: 2840 },
  { month: '2025-08', metric: 'Active Users (MAU)', count: 3120 },
  { month: '2025-09', metric: 'Active Users (MAU)', count: 3510 },
  { month: '2025-10', metric: 'Active Users (MAU)', count: 3940 },
  { month: '2025-11', metric: 'Active Users (MAU)', count: 4410 },
  { month: '2025-12', metric: 'Active Users (MAU)', count: 4980 },
];

const engagementData = [
  { month: '2025-01', engagement_score: 54.2 },
  { month: '2025-02', engagement_score: 56.8 },
  { month: '2025-03', engagement_score: 58.4 },
  { month: '2025-04', engagement_score: 59.8 },
  { month: '2025-05', engagement_score: 60.2 },
  { month: '2025-06', engagement_score: 61.4 },
  { month: '2025-07', engagement_score: 62.4 },
  { month: '2025-08', engagement_score: 65.1 },
  { month: '2025-09', engagement_score: 68.3 },
  { month: '2025-10', engagement_score: 71.2 },
  { month: '2025-11', engagement_score: 73.8 },
  { month: '2025-12', engagement_score: 76.4 },
];

const mockQueryFn: QueryFn = async (sql) => {
  if (sql.includes('product_metrics') && sql.includes('mrr')) {
    return mrrData;
  }
  if (sql.includes('user_metrics')) {
    return userGrowthData;
  }
  if (sql.includes('product_metrics') && sql.includes('engagement_score')) {
    return engagementData;
  }
  return [];
};

function DynamicReportStory() {
  const [processedContent, setProcessedContent] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    executeReport(DYNAMIC_REPORT, mockQueryFn)
      .then((result) => {
        if (!cancelled) {
          setProcessedContent(result);
          setIsLoading(false);
        }
      })
      .catch((err: unknown) => {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : String(err));
          setIsLoading(false);
        }
      });

    return () => {
      cancelled = true;
    };
  }, []);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center p-16">
        <div className="text-muted-foreground text-sm">Executing report…</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-destructive/10 text-destructive m-8 rounded-md p-4 text-sm">
        <strong>Error executing report:</strong> {error}
      </div>
    );
  }

  if (!processedContent) return null;

  return <ReportRenderer content={processedContent} />;
}

export const DynamicReport: Story = {
  render: () => <DynamicReportStory />,
};
