#!/usr/bin/env bash
# Provision a per-worktree preview environment for an SDD story.
#
# Invoked by `/start-story` after `git worktree add`. Idempotent.
#
# Usage: scripts/sdd/setup-preview.sh <NNN> <worktree-path>
#
# Does:
#   1. Computes deterministic ports for this NNN (via preview-ports.sh).
#   2. Writes <worktree>/.preview.env — single source of truth for the worktree.
#   3. Copies apps/web/.env.local and apps/server/.env from the main repo,
#      rewriting port-bound lines (VITE_SUPABASE_URL, SUPABASE_URL, EMAIL_PORT,
#      VITE_DEV_API_PROXY) to the worktree's ports.
#   4. Patches <worktree>/apps/web/supabase/config.toml: project_id + port
#      fields. This is a worktree-local file; main's copy is untouched.
#
# Never pushes, never touches a remote, never runs pnpm/supabase itself.

set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: setup-preview.sh <NNN> <worktree-path>" >&2
  exit 1
fi

NNN_RAW="$1"
WORKTREE="$2"

if [[ ! -d "$WORKTREE" ]]; then
  echo "setup-preview.sh: worktree not found: $WORKTREE" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAIN_REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"

# shellcheck source=./preview-ports.sh
source "$SCRIPT_DIR/preview-ports.sh" "$NNN_RAW"

PREVIEW_ENV="$WORKTREE/.preview.env"

# Belt-and-suspenders: ensure this worktree hides .preview.env even if its
# branch was forked before main's .gitignore rule landed. Per-worktree exclude
# file lives in this worktree's own GIT_DIR (under $MAIN_REPO/.git/worktrees/).
WT_GIT_DIR="$(cd "$WORKTREE" && git rev-parse --git-dir)"
EXCLUDE_FILE="$WT_GIT_DIR/info/exclude"
mkdir -p "$WT_GIT_DIR/info"
touch "$EXCLUDE_FILE"
if ! grep -qxF ".preview.env" "$EXCLUDE_FILE"; then
  printf '\n# SDD per-worktree preview env\n.preview.env\n' >> "$EXCLUDE_FILE"
fi

cat > "$PREVIEW_ENV" <<EOF
# Generated by scripts/sdd/setup-preview.sh — do not edit by hand.
# Story NNN: $NNN_RAW
#
# source this file to run dev servers / supabase for this worktree without
# clashing with the main repo or sibling worktrees.
export WEB_PORT=$WEB_PORT
export SERVER_PORT=$SERVER_PORT
export VITE_DEV_API_PROXY=http://localhost:$SERVER_PORT
export SB_API=$SB_API
export SB_DB=$SB_DB
export SB_STUDIO=$SB_STUDIO
export SB_INBUCKET=$SB_INBUCKET
export SB_SMTP=$SB_SMTP
export SB_POP3=$SB_POP3
export SB_SHADOW=$SB_SHADOW
export SB_ANALYTICS=$SB_ANALYTICS
export SUPABASE_PROJECT_ID=$SUPABASE_PROJECT_ID
export VITE_SUPABASE_URL=http://127.0.0.1:$SB_API
export SUPABASE_URL=http://127.0.0.1:$SB_API
export EMAIL_PORT=$SB_SMTP
EOF

rewrite_env_line() {
  local file="$1" key="$2" value="$3"
  if grep -q "^${key}=" "$file"; then
    # macOS sed needs '' after -i; portable variant: sed -i.bak then rm bak
    sed -i.bak -E "s|^${key}=.*$|${key}=${value}|" "$file"
    rm -f "${file}.bak"
  else
    printf '\n%s=%s\n' "$key" "$value" >> "$file"
  fi
}

# apps/web/.env.local — copy main's and override port-bound entries.
WEB_SRC="$MAIN_REPO/apps/web/.env.local"
WEB_DST="$WORKTREE/apps/web/.env.local"
if [[ -f "$WEB_SRC" ]]; then
  cp "$WEB_SRC" "$WEB_DST"
else
  cp "$WORKTREE/apps/web/.env.example" "$WEB_DST"
fi
rewrite_env_line "$WEB_DST" "VITE_SUPABASE_URL" "http://127.0.0.1:$SB_API"
rewrite_env_line "$WEB_DST" "VITE_DEV_API_PROXY" "http://localhost:$SERVER_PORT"
rewrite_env_line "$WEB_DST" "EMAIL_PORT" "$SB_SMTP"
rewrite_env_line "$WEB_DST" "VITE_SITE_URL" "http://localhost:$WEB_PORT"

# apps/server/.env — same treatment.
SRV_SRC="$MAIN_REPO/apps/server/.env"
SRV_DST="$WORKTREE/apps/server/.env"
if [[ -f "$SRV_SRC" ]]; then
  cp "$SRV_SRC" "$SRV_DST"
else
  cp "$WORKTREE/apps/server/.env.example" "$SRV_DST"
fi
rewrite_env_line "$SRV_DST" "SUPABASE_URL" "http://127.0.0.1:$SB_API"

# apps/web/supabase/config.toml — patch project_id and port lines.
# The worktree has its own copy, so these edits are contained.
SB_CFG="$WORKTREE/apps/web/supabase/config.toml"
if [[ -f "$SB_CFG" ]]; then
  sed -i.bak -E \
    -e "s|^project_id = .*|project_id = \"$SUPABASE_PROJECT_ID\"|" \
    "$SB_CFG"
  # Port substitutions: we key off each section's first 'port = <int>' line.
  python3 - "$SB_CFG" "$SB_API" "$SB_DB" "$SB_STUDIO" "$SB_INBUCKET" "$SB_SMTP" "$SB_POP3" <<'PY'
import re, sys
path, api, db, studio, inbucket, smtp, pop3 = sys.argv[1:]
text = open(path).read()
# Per-section port: [api].port, [db].port, [studio].port
def replace_section_port(text, section, port):
    pattern = re.compile(rf'(\[{section}\][^\[]*?\bport\s*=\s*)\d+', re.DOTALL)
    return pattern.sub(rf'\g<1>{port}', text, count=1)
text = replace_section_port(text, 'api', api)
text = replace_section_port(text, 'db', db)
text = replace_section_port(text, 'studio', studio)
# [inbucket] has three ports: port, smtp_port, pop3_port.
def replace_named_port(text, section, name, port):
    pattern = re.compile(rf'(\[{section}\][^\[]*?\b{name}\s*=\s*)\d+', re.DOTALL)
    return pattern.sub(rf'\g<1>{port}', text, count=1)
text = replace_named_port(text, 'inbucket', 'port', inbucket)
text = replace_named_port(text, 'inbucket', 'smtp_port', smtp)
text = replace_named_port(text, 'inbucket', 'pop3_port', pop3)
# Auth site_url / additional_redirect_urls still reference 3000; not changing
# that here — the worktree's WEB_PORT doesn't affect magic-link flows in dev
# unless the user signs in from that port. Flagged as a follow-up in docs.
open(path, 'w').write(text)
PY
  rm -f "${SB_CFG}.bak"
  # Hide the port-patched config.toml from git status in this worktree so
  # `/finish`'s "changes outside files: allowlist" check stays clean. The file
  # stays tracked on main; only this worktree's index is told to ignore edits.
  ( cd "$WORKTREE" && git update-index --skip-worktree apps/web/supabase/config.toml 2>/dev/null || true )
fi

cat <<EOF
[setup-preview] worktree: $WORKTREE
  WEB_PORT=$WEB_PORT  SERVER_PORT=$SERVER_PORT
  SB_API=$SB_API (API)  SB_DB=$SB_DB  SB_STUDIO=$SB_STUDIO
  SB_INBUCKET=$SB_INBUCKET  SB_SMTP=$SB_SMTP  SB_POP3=$SB_POP3
  SUPABASE_PROJECT_ID=$SUPABASE_PROJECT_ID
Source it:  cd "$WORKTREE" && set -a && . ./.preview.env && set +a
Then run:   pnpm preview
EOF
